updates

diff --git a/.github/workflows/build-and-upload-package.yml b/.github/workflows/build-and-upload-package.yml
--- a/.github/workflows/build-and-upload-package.yml
+++ b/.github/workflows/build-and-upload-package.yml
@@ -23,6 +23,15 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v3
 
+      - name: List files and directories for debug
+        run: |
+          echo "Listing root directory contents:"
+          ls -l
+          echo "Listing cloudformation directory contents:"
+          ls -l cloudformation || echo "cloudformation directory not found"
+          echo "Listing forge-files directory contents:"
+          ls -l forge-files || echo "forge-files directory not found"
+
       - id: package-default-version
         name: Get Default Version outputs
         run: echo "::set-output name=version::$(date +'%Y%m%d%H%M%S')"
@@ -34,7 +43,7 @@ jobs:
           cp -r cloudformation forge-files scripts README.md package/
           cd package
           zip -r ../${{ steps.package-default-version.outputs.version }}.zip ./
-          cd ..
+          cd .. 
 
       - id: package-upload
         name: Upload Package
